Proposal model, repository, services and DTO made
ayudadigital/huelladigital-frontend pull request #19
Opened 2020-11-23 11:53 UTC by Samuel-AQ

## Proposed changes

The proposal repository, DTO and services have been updated.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

The ProposalDTO interface wasn't been used as it should in the repository so it was changed in the repository file.

2020-11-23 15:29 UTC, javidiazdom requested changes
Hola Samu! 
Antes de aprobar la pull request, debes corregir algunas cositas.
- __Prettier__
Debes activar el formateo de código en tu editor, para que cuando guardes un fichero se formatee de acuerdo a la configuración de prettier que tiene el proyecto. Así estandarizamos nuestra sintaxis.
- __Instalación de módulos innecesarios__
Los cambios introducidos a package-lock.json y package.json no son necesarios para el funcionamiento de tu refactor, por lo que deberías corregirlos.

2020-11-23 15:29 UTC, javidiazdom commented on frontend/src/infrastructure/components/atoms/LinkButton/types.ts
> +}
Missing prettier formating

2020-11-23 15:29 UTC, javidiazdom commented on frontend/src/infrastructure/components/organisms/Forms/FormRegisterOrganization/FormRegisterOrganization.tsx
> -}
Realmente es necesaria la creación de nuevos ficheros? Estos tipos van a ser reutilizados?

2020-11-23 15:29 UTC, javidiazdom commented on frontend/package.json
> +    "node-sass": "^4.14.1",
Este paquete no debería de haber sido actualizado.

2020-11-23 22:14 UTC, Samuel-AQ commented on frontend/src/infrastructure/components/organisms/Forms/FormRegisterOrganization/FormRegisterOrganization.tsx
> -}
Si no vi mal el fichero se supone se usa para tipar los states de FormRegisterOrganization. Lo separé en un fichero types por organización porque también lo había visto en algunos componentes de tipo átomo. Qué sugieres que es mejor hacer?

2020-11-23 22:26 UTC, Samuel-AQ commented on frontend/src/infrastructure/components/atoms/LinkButton/types.ts
> +}
Es solo en este fichero o has visto la diferencia de formato en más ficheros?

2020-11-25 09:57 UTC, javidiazdom approved these changes

2020-11-25 09:57 UTC, merged