Fix select date proposal only start date
ayudadigital/huelladigital-frontend pull request #21
Opened 2020-11-28 17:23 UTC by Oiranca

## Proposed changes

Checking if start day is correct. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

To check start date i make a function where, first check  the year is bigger, then the month and finally the day. I don't make this check with getTime method why this method check the hours too.

2020-11-30 12:16 UTC, javidiazdom requested changes
Hola Samu! Está muy bien, sólo me gustaría que cambiaras el alert por algo un poco más elegante, como una notificación en un <div>. Además, también me gustaría que le echaras un vistazo a lo que puedes hacer con el tipo Date de typescript, seguro que la comparación es más sencilla.

2020-11-30 12:16 UTC, javidiazdom commented on frontend/src/infrastructure/view/pages/Convocations/ConvocatoryRegister/ConvocatoryRegister.tsx
> +      : alert('Formato Fecha incorrecto');
Nunca utilizamos alert! 🙊

2020-11-30 12:16 UTC, javidiazdom commented on frontend/src/infrastructure/view/pages/Convocations/ConvocatoryRegister/ConvocatoryRegister.tsx
> +    }
El separador es necesario obtenerlo así? No es siempre el mismo ?

2020-11-30 12:16 UTC, javidiazdom commented on frontend/src/infrastructure/view/pages/Convocations/ConvocatoryRegister/ConvocatoryRegister.tsx
> +
Puedes hacer la comparación mucho más elegante utilizando el[ tipo Date](https://www.javatpoint.com/typescript-date-object) de Typescript

2020-11-30 12:17 UTC, Oiranca commented on frontend/src/infrastructure/view/pages/Convocations/ConvocatoryRegister/ConvocatoryRegister.tsx
> +      : alert('Formato Fecha incorrecto');
Ok, lo quito, que puedo poner??

2020-11-30 12:18 UTC, Oiranca commented on frontend/src/infrastructure/view/pages/Convocations/ConvocatoryRegister/ConvocatoryRegister.tsx
> +    }
en un principio si, pero si lo cambiamos?? me pareció más seguro buscarlo

2020-12-01 10:44 UTC, javidiazdom reviewed
Okey, está muy bien. Como tú bien dices, aún se puede mejorar: No es necesario separar las fechas en 3 variables, si utilizas el separador correcto es capaz de parsear una string. Podrías apuntarlo como una futura mejora.

2020-12-01 10:46 UTC, javidiazdom approved these changes
This is fine. It has room for improvement: dates are created splitting strings unnecesarily, Date constructor allows using string-formated dates as parameters.

2020-12-01 12:07 UTC, merged