New component register esal
ayudadigital/huelladigital-frontend pull request #42
Opened 2020-12-22 09:23 UTC by Oiranca

## Proposed changes

Added radio ande checkbox into type.ts from InpuntFieldForm, created molecules with name FormRadio and created two organisms FormRegisterContactPerson and FormRegisterEsal.

## Types of changes

What types of changes does your code introduce to HuellaPositiva?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, 
don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging 
your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-22 09:27 UTC, Oiranca commented on frontend/src/infrastructure/repositories/Convocatory.repository.test.ts
> -      organizer: 'Example Esal',
Se cambió al hacer le refactor name, no es nada importarte porque son los nombres del ejemplo

2020-12-23 09:40 UTC, javidiazdom requested changes
Sería interesante que le echaras un vistazo a la creación de los FormRadios en Form Register Esal. Estoy seguro de que se puede reducir el tamaño del archivo con un bucle.

2020-12-23 09:40 UTC, javidiazdom commented on frontend/src/infrastructure/view/components/organisms/Forms/FormRegisterEsal/FormRegisterEsal.tsx
> +                      />
Duplicidad de código innecesaria. ¿No podrías introducir esto en bucle que itere sobre los nombres de las diferentes islas?

2020-12-23 13:46 UTC, javidiazdom approved these changes
Correct, this is much better.

2020-12-23 13:47 UTC, merged