Home view has been updated following the current design of the web
ayudadigital/huelladigital-frontend pull request #46
Opened 2020-12-31 12:38 UTC by Samuel-AQ

## Proposed changes

Home view has been updated following the current design of the web

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

There is much more to do, this is just the view. The logic and the refactor will be applied soon.

2021-01-04 11:47 UTC, javidiazdom commented
Great job! At a first glance the new page on storybook looks really nice. Ill take a look now at the code.

2021-01-04 12:38 UTC, javidiazdom requested changes
The homepage design is awesome. Just take a look at that parameters on the Image component and correct me if Im wrong, of course.

2021-01-04 12:38 UTC, javidiazdom commented on frontend/src/infrastructure/view/components/atoms/Image/Image.tsx
> +}) => <img src={source} alt={description} width={width} className={cssClass} />;
Why pass the CSS class and height as parameters? This is not needed. Styles can be applied on parent components where this component is used.

2021-01-04 12:38 UTC, javidiazdom commented on frontend/src/infrastructure/view/components/atoms/Image/types.ts
> +  cssClass?: string;
Same as before. Unnecesary parameters?

2021-01-04 13:31 UTC, Samuel-AQ commented on frontend/src/infrastructure/view/components/atoms/Image/Image.tsx
> +}) => <img src={source} alt={description} width={width} className={cssClass} />;
Sorry, I wrote that in order to test something I wanted to test but in the end I didn't use it and left it there. I'm going to fix it and commit again.

2021-01-04 13:32 UTC, Samuel-AQ commented on frontend/src/infrastructure/view/components/atoms/Image/types.ts
> +  cssClass?: string;
It's the same issue. I'm going to fix it and commit again.

2021-01-07 13:50 UTC, javidiazdom approved these changes

2021-01-07 13:50 UTC, merged